-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsg6pduldp+N0XBI9
359cv7ArUmHgdbOMEpeT4fHRFaCgCgYIKoZIzj0DAQehRANCAATyr5aJ5iLBgwGU
Wt/PCpJATAaxiQgFNJ8FJT/vOGvdypHRIhRlwPmqHMCQbhlTOH7MKjJqVOafbcZt
s/ehaQKe
-----END PRIVATE KEY-----